### ISSUE TITLE
How to get the FPGA prototype in Firemarshal？

### ISSUE THREAD

**Issue by L-Chocoland** [ucb-bar/chipyard#1039]
I'm trying to build FPGA prototype in my own VMware linux.
But many problems occured and disturb me many days.
my enviroment: Ubuntu 18.04 or centos 7. follow the chipyard tutorial.

First I try to build chipyard in Ubuntu,it work's well.
but when i do
./marshal -v -d build br-base.json, there have several problems.
i follow the README, Avoid #30 happen.
But when i exectute the above line,the VMware machine crashed the system every time.
Sometimes tell me it is out of memory.Sometime it doesn't have any output just crashed and restart system.Even I gave the VMware 40GB memory, it's still crashed.

So i turn to Centos 7.
But when i followed the chipyard tutorial to do ./scripts/build-toolchains.sh riscv-tools, it reminds me I need GNU make 4.x。
It seems the tutorials which in https://chipyard.readthedocs.io/en/latest/Chipyard-Basics/Initial-Repo-Setup.html about Centos doesn't work well, but i confirmed that i do those orders.
So i rebuild make ,and then build riscv-tools.
But when i do ./marshal -v -d build br-base.json , Something happened.

DEBUG: make[3]: *** No rule to make target '../lib/libext2fs.so', needed by 'e2fsck'. Stop.
DEBUG: make[3]: *** Waiting for unfinished jobs....
DEBUG: make[3]: Leaving directory '/home/ljq/chipyard/software/firemarshal/boards/default/distros/br/buildroot/output/build/e2fsprogs-1.45.2/e2fsck'
DEBUG: make[2]: *** [Makefile:434: all-progs-recursive] Error 1
DEBUG: make[2]: Leaving directory '/home/ljq/chipyard/software/firemarshal/boards/default/distros/br/buildroot/output/build/e2fsprogs-1.45.2'
DEBUG: make[1]: *** [Makefile:368: all] Error 2
DEBUG: make[1]: Leaving directory '/home/ljq/chipyard/software/firemarshal/boards/default/distros/br/buildroot/output/build/e2fsprogs-1.45.2'
DEBUG: make: *** [package/pkg-generic.mk:241: /home/ljq/chipyard/software/firemarshal/boards/default/distros/br/buildroot/output/build/e2fsprogs-1.45.2/.stamp_built] Error 2
TaskError - taskid:/home/ljq/chipyard/software/firemarshal/images/br.79c0.img
PythonAction Error
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/doit/action.py", line 437, in execute
returned_value = self.py_callable(*self.args, **kwargs)
File "/home/ljq/chipyard/software/firemarshal/boards/prototype/distros/br/br.py", line 190, in buildBaseImage
wlutil.run(['make'], cwd=br_dir / "buildroot", env=env)
File "/home/ljq/chipyard/software/firemarshal/wlutil/wlutil.py", line 498, in run
raise sp.CalledProcessError(p.returncode, prettyCmd)
subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.

ERROR: Failed to build workload br-base.json

it happened before when i use the AWS instance.i have an issue in firesim when its happen.firesim/firesim#861

So i think the rebuild make cause this problem. But it is a Dead Cycle. IF I do not rebuild make ,I wouldn't build riscv-tools.

I want to ask How to fix it? or How did your guys get the FPGA prototype ？

I opened the same question in https://github.com/firesim/FireMarshal/issues/215 maybe someone can help me.

**Comment by L-Chocoland** [comment]
To precisely,My goal is to run linux on VCU118.
I have been generate bitstream in Vivado followed the chipyard tutorial.
And first I generated br-base-no-disk-flat in AWS instance,using firemarshal.
But i got a problem when run linux on VCU118.
When the screen shows:
MIDELEG : 0x0000000000000222
MEDELEG : 0x000000000000b109
PMP0 : 0x0000000080000000-0x000000008001ffff (A)
PMP1 : 0x0000000000000000-0x00000001ffffffff (A,R,W,X)
it does not output any things.
follow the issue: https://github.com/ucb-bar/chipyard/issues/957
i think something wrong in the Firemarshal image.So i think it should be down in my environment,not Firemarshal in AWS instance and ec2fast tools.
so I want to get FPGA prototype in my VMware machine and meet problem i talked above. 
hoping for reply

**Comment by L-Chocoland** [comment]
question has been answered in https://github.com/firesim/FireMarshal/issues/215. close
