### ISSUE TITLE
Firemarshal and NVDLA: failure after executing guestunmount

### ISSUE THREAD

**Issue by Flipfle** [ucb-bar/chipyard#1093]
**Impact**: software

**Tell us about your environment:**
*Chipyard Version:*  master branch, newest Hash: 02adf86

*OS:* 
CentOS Linux 8, 64 bit
I work on a server, so I don’t have sudo permissions.

*Other:* 
I installed Chipyard like in „1.4. Initial Repository Setup“ written. I want to execute CNNs on an NVDLA using Firemarshal. 

I followed orders in the **ReadMe.md** in directory ``nvdla-workload``. So, I edited the Kconfig file in ``software/firemarshal/boards/default/linux/drivers/gpu/drm`` and replaced ``bool``with ``bool "GEM CMA Helper Functions“`` under ``config DRM_GEM_CMA_HELPER`` . Additionally, I checked out in ``software/firemarshal/boards/linux`` to branch ``nvdla-linux-v57``.

I executed the command 
``./marshal -v build /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/nvdla-workload/marshal-configs/nvdla-large-resnet50.json``.
I just took this workload to understand how everything works.

**What is the current behavior?**
The program runs into an error when it tries to unmount the ``disk-mount``.  

**What is the expected behavior?**
This command should run without an error.

**Other information**

The last lines of the output are:
```log
DEBUG: Running: "cp -a /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/boards/firechip/base-workloads/br-base/overlay/etc /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/disk-mount22_04" in /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal
DEBUG: Running: "cp -a /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/boards/firechip/base-workloads/br-base/overlay/usr /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/disk-mount22_04" in /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal
DEBUG: Running: "guestunmount /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/disk-mount22_04" in /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal
DEBUG: guestunmount: failed to unmount /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/disk-mount22_04: fusermount: failed to chdir to /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal: Permission denied
DEBUG: BEN.        PID ZUGR.  BEFEHL
DEBUG: /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/disk-mount22_04:
DEBUG: root     kernel mount /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/disk-mount22_04
TaskError - taskid:/home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/images/br-base.img
PythonAction Error
Traceback (most recent call last):
  File "/home/ulnor/.local/lib/python3.6/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/wlutil/build.py", line 564, in makeImage
    applyOverlay(config['img'], config['overlay'])
  File "/home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/wlutil/wlutil.py", line 621, in applyOverlay
    copyImgFiles(img, flist, 'in')
  File "/home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/wlutil/wlutil.py", line 611, in copyImgFiles
    raise ValueError("direction option must be either 'in' or 'out'")
  File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/wlutil/wlutil.py", line 543, in mountImg
    run(['guestunmount', mntPath])
  File "/home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/wlutil/wlutil.py", line 498, in run
    raise sp.CalledProcessError(p.returncode, prettyCmd)
subprocess.CalledProcessError: Command 'guestunmount /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/disk-mount22_04' returned non-zero exit status 2.

ERROR: Failed to build workload nvdla-large-resnet50.json
Log available at: /home/ulnor/Dokumente/micro_Kernel_project/00_Repos/chipyard/software/firemarshal/logs/nvdla-large-resnet50-build-2022-01-20--14-08-09-FMRS3FXW2NUIAB1Q.log

```
(I renamed ``disk-mount`` to ``disk-mount22_04`` due to accessing problems due to I killed the process guestmount.)

The copy-commands before the erroneous command worked perfectly.

I googled for similar errors and couldn’t found help. I am new to this project and never used ``guestmount`` before. So I think I missed something but cannot tell what.. Can anyone help me, please?

**Comment by Yuxin-Yu** [comment]
Hi @Flipfle .Have you sovle this problem?
