### ISSUE TITLE
error while running the basic fast memory load and generating waveforms

### ISSUE THREAD

**Issue by kahretsinanil** [ucb-bar/chipyard#1186]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.5.0
Hash: a6a6a6

### OS Setup

Output of `uname -a` and `lsb_release -a`:
Linux ubuntu 5.13.0-48-generic #54~20.04.1-Ubuntu SMP Thu Jun 2 23:37:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...
chipyard latest documentary, step 2.1.6-2.1.7-2.1.8

### Current Behavior

When i try to simulating a custom project, like `make SUB_PROJET=project1` I got this error:
`
[error] (run-main-0) java.lang.ClassNotFoundException: /Generator
[error] java.lang.ClassNotFoundException: /Generator
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:398)
[error] stack trace is suppressed; run last Compile / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 0 s, completed Jun 19, 2022, 10:31:48 PM
make: *** [/home/anil/Desktop/rocketchip/chipyard/common.mk:111: generator_temp] Error 1
`
even if I try to run  `make SUB_PROJECT=hwacha`, I always take the similar error.

If I try to execute the fast memory loading, the following error alyas taken,
`make run-binary BINARY=test.riscv LOADMEM=testdata.hex LOADMEM_ADDR=81000000`
Error:
`
root@ubuntu:/home/anil/Desktop/rocketchip/chipyard/sims/verilator# make run-binary BINARY=test.riscv LOADMEM=testdata.hex LOADMEM_ADDR=81000000
Running with RISCV=/home/anil/Desktop/rocketchip/chipyard/riscv-tools-install
(set -o pipefail &&  /home/anil/Desktop/rocketchip/chipyard/sims/verilator/simulator-chipyard-RocketConfig +permissive +dramsim +dramsim_ini_dir=/home/anil/Desktop/rocketchip/chipyard/generators/testchipip/src/main/resources/dramsim2_ini +max-cycles=10000000 +loadmem=testdata.hex +loadmem_addr=81000000   +verbose +permissive-off test.riscv </dev/null 2> >(spike-dasm > /home/anil/Desktop/rocketchip/chipyard/sims/verilator/output/chipyard.TestHarness.RocketConfig/test.out) | tee /home/anil/Desktop/rocketchip/chipyard/sims/verilator/output/chipyard.TestHarness.RocketConfig/test.log)
[UART] UART0 is here (stdin/stdout).
make: *** [/home/anil/Desktop/rocketchip/chipyard/common.mk:206: run-binary] Error 255
`

After that, when I try to run `make run-binary-hex BINARY=test.riscv ` 
I take the following error:
`
root@ubuntu:/home/anil/Desktop/rocketchip/chipyard/sims/verilator# make run-binary-hex BINARY=test.riscv
Running with RISCV=/home/anil/Desktop/rocketchip/chipyard/riscv-tools-install
make: *** No rule to make target 'test.riscv', needed by '/home/anil/Desktop/rocketchip/chipyard/sims/verilator/output/chipyard.TestHarness.RocketConfig/test.loadmem_hex'.  Stop.
`

But the `make run-asm-tests` and  `make run-bmark-tests` are works for me.

And the last part of this section, when I try to execute make or make debug in `rocketchip/chipyard/sims/verilator`,
I am getting this error but in my previous work I took the vcd file but gtkwave didn't show any waveform.
`Running with RISCV=/home/anil/Desktop/rocketchip/chipyard/riscv-tools-install
make: Nothing to be done for 'debug'.`

`Running with RISCV=/home/anil/Desktop/rocketchip/chipyard/riscv-tools-install
make: Nothing to be done for 'default'.`

### Expected Behavior

I start to work with chipyard very new and I have no experience with that. Why these errors occurs every single of my try? I've already tried the fresh start but the results does not change.

### Other Information

When I execute the `make debug` in `verilator` file, the inside of the vcd file can be shown in that link:
https://gist.github.com/kahretsinanil/eed433fb64465f6d7443fd04c2d2455f

**Comment by kahretsinanil** [comment]
after implementing a custom project like which include in HeteroConfig file, the task has been done.
the issue is closed.
