### ISSUE TITLE
encounter error when run build_verilator.sh in gemmini/scripts

### ISSUE THREAD

**Issue by Charles-Tang** [ucb-bar/chipyard#1289]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Hash: 117624d8eea27bafd613eec09e9b9b3e31239e08

### OS Setup

Debian 11

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...

### Current Behavior

./scripts/build-verilator.sh --debug
Running with RISCV=/usr/local/riscv
cd /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard && java -jar /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/generators/rocket-chip/sbt-launch.jar -Dsbt.override.build.repos=true  ";project tapeout; runMain barstools.tapeout.transforms.GenerateTopAndHarness  --allow-unrecognized-annotations --output-file /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.top.v --harness-o /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.harness.v --input-file /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.fir --syn-top ChipTop --harness-top TestHarness --annotation-file /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.anno.json --top-anno-out /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.top.anno.json --top-dotf-out /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/firrtl_black_box_resource_files.top.f --top-fir /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.top.fir --harness-anno-out /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.harness.anno.json --harness-dotf-out /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/firrtl_black_box_resource_files.harness.f --harness-fir /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.harness.fir --infer-rw --repl-seq-mem -c:TestHarness:-o:/media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.top.mems.conf -thconf /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig/chipyard.TestHarness.CustomGemminiSoCConfig.harness.mems.conf --target-dir /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/verilator/generated-src/chipyard.TestHarness.CustomGemminiSoCConfig --log-level error "
Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Djava.io.tmpdir=/media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/.java_tmp
[info] welcome to sbt 1.5.5 (Oracle Corporation Java 1.8.0_321)
[info] loading settings for project chipyard-build from plugins.sbt ...
[info] loading project definition from /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/project
[info] loading settings for project chipyardRoot from build.sbt ...
[info] loading settings for project hardfloat from build.sbt ...
[info] loading settings for project rocketConfig from build.sbt ...
[info] loading settings for project testchipip from build.sbt ...
[info] loading settings for project icenet from build.sbt ...
[info] loading settings for project hwacha from build.sbt ...
[info] loading settings for project boom from build.sbt ...
[info] loading settings for project cva6 from build.sbt ...
[info] loading settings for project ibex from build.sbt ...
[info] loading settings for project sodor from build.sbt ...
[info] loading settings for project gemmini from build.sbt ...
[info] loading settings for project tapeout from build.sbt ...
[info] loading settings for project sim-build from plugins.sbt ...
[info] loading project definition from /media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/sims/firesim/sim/project
[info] loading settings for project firesim from build.sbt ...
[info] loading settings for project targetutils from build.sbt ...
[info] loading settings for project midas from build.sbt ...
[info] resolving key references (32290 settings) ...
[info] set current project to chipyardRoot (in build file:/media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/)
[info] set current project to tapeout (in build file:/media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:chisel3_2.12:3.5-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/charles/.ivy2/localedu.berkeley.cs/chisel3_2.12/3.5-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.huaweicloud.com/repository/maven/edu/berkeley/cs/chisel3_2.12/3.5-SNAPSHOT/chisel3_2.12-3.5-SNAPSHOT.pom
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/chisel3_2.12/3.5-SNAPSHOT/chisel3_2.12-3.5-SNAPSHOT.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/edu.berkeley.cs/chisel3_2.12/3.5-SNAPSHOT/ivys/ivy.xml
[error] Error downloading edu.berkeley.cs:chisel-iotesters_2.12:2.5-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/charles/.ivy2/localedu.berkeley.cs/chisel-iotesters_2.12/2.5-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.huaweicloud.com/repository/maven/edu/berkeley/cs/chisel-iotesters_2.12/2.5-SNAPSHOT/chisel-iotesters_2.12-2.5-SNAPSHOT.pom
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/chisel-iotesters_2.12/2.5-SNAPSHOT/chisel-iotesters_2.12-2.5-SNAPSHOT.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/edu.berkeley.cs/chisel-iotesters_2.12/2.5-SNAPSHOT/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:chisel3_2.12:3.5-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/charles/.ivy2/localedu.berkeley.cs/chisel3_2.12/3.5-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.huaweicloud.com/repository/maven/edu/berkeley/cs/chisel3_2.12/3.5-SNAPSHOT/chisel3_2.12-3.5-SNAPSHOT.pom
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/chisel3_2.12/3.5-SNAPSHOT/chisel3_2.12-3.5-SNAPSHOT.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/edu.berkeley.cs/chisel3_2.12/3.5-SNAPSHOT/ivys/ivy.xml
[error] Error downloading edu.berkeley.cs:chisel-iotesters_2.12:2.5-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/charles/.ivy2/localedu.berkeley.cs/chisel-iotesters_2.12/2.5-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo.huaweicloud.com/repository/maven/edu/berkeley/cs/chisel-iotesters_2.12/2.5-SNAPSHOT/chisel-iotesters_2.12-2.5-SNAPSHOT.pom
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/chisel-iotesters_2.12/2.5-SNAPSHOT/chisel-iotesters_2.12-2.5-SNAPSHOT.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/edu.berkeley.cs/chisel-iotesters_2.12/2.5-SNAPSHOT/ivys/ivy.xml
[error] Total time: 21 s, completed 2022-12-15 15:33:02
make: *** [/media/charles/0F6215370F621537/Files/BachelorDesign/chipyard/common.mk:137：firrtl_temp] 错误 1

### Expected Behavior

should run without errors

**Comment by Charles-Tang** [comment]
Well, I find the source of the error, in chipyard/tools/barstools/build.sbt, the version of chisel and chisel tester is a SNAPSHOT version which is not exist, change to a valid version like 3.5.1&2.5.1 will solve the problem
