### ISSUE TITLE
sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.10:4.3.22

### ISSUE THREAD

**Issue by JHyellow** [ucb-bar/chipyard#1379]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.8.1

### OS Setup

Ex: Output of `uname -a` + `lsb_release -a` + `printenv` + `conda list`

Linux riscv 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

SHELL=/bin/bash
SESSION_MANAGER=local/riscv:@/tmp/.ICE-unix/8351,unix/riscv:/tmp/.ICE-unix/8351
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_MENU_PREFIX=gnome-
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GTK_IM_MODULE=fcitx
CONDA_EXE=/home/huang/miniforge3/bin/conda
_CE_M=
LANGUAGE=en_US:en
QT4_IM_MODULE=fcitx
LC_ADDRESS=zh_CN.UTF-8
GNOME_SHELL_SESSION_MODE=ubuntu
LC_NAME=zh_CN.UTF-8
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XMODIFIERS=@im=fcitx
DESKTOP_SESSION=ubuntu
LC_MONETARY=zh_CN.UTF-8
SSH_AGENT_PID=8308
GTK_MODULES=gail:atk-bridge
DBUS_STARTER_BUS_TYPE=session
PWD=/home/huang/clonehub/chipyard/sims/verilator
GSETTINGS_SCHEMA_DIR=/home/huang/miniforge3/envs/chipyard/share/glib-2.0/schemas
LOGNAME=huang
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_TYPE=x11
CONDA_PREFIX=/home/huang/miniforge3/envs/chipyard
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
XAUTHORITY=/run/user/1000/gdm/Xauthority
WINDOWPATH=2
HOME=/home/huang
USERNAME=huang
IM_CONFIG_PHASE=1
LC_PAPER=zh_CN.UTF-8
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=ubuntu:GNOME
VTE_VERSION=6003
CONDA_PROMPT_MODIFIER=(chipyard) 
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/3de39482_3598_46cc_b9c0_d129eabea1a5
INVOCATION_ID=ff1592da7ab044a7912f6443fb0cbd30
MANAGERPID=8136
CLUTTER_IM_MODULE=fcitx
XDG_SESSION_CLASS=user
TERM=xterm-256color
LC_IDENTIFICATION=zh_CN.UTF-8
_CE_CONDA=
USER=huang
GNOME_TERMINAL_SERVICE=:1.223
CONDA_SHLVL=2
DISPLAY=:0
SHLVL=1
LC_TELEPHONE=zh_CN.UTF-8
QT_IM_MODULE=fcitx
LC_MEASUREMENT=zh_CN.UTF-8
DBUS_STARTER_ADDRESS=unix:path=/run/user/1000/bus,guid=29ae878d297064bb63f3816e64005990
PAPERSIZE=a4
CONDA_PYTHON_EXE=/home/huang/miniforge3/bin/python
XDG_RUNTIME_DIR=/run/user/1000
CONDA_DEFAULT_ENV=chipyard
LC_TIME=zh_CN.UTF-8
JOURNAL_STREAM=8:56975
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
PATH=/home/huang/miniforge3/envs/chipyard/bin:/home/huang/miniforge3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/huang/clonehub/RISCV/riscv/bin:/opt/riscv/bin:/home/huang/clonehub/RISCV/riscv/bin:/opt/riscv/bin:/usr/local/sbt
GDMSESSION=ubuntu
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus,guid=29ae878d297064bb63f3816e64005990
CONDA_PREFIX_1=/home/huang/miniforge3
LC_NUMERIC=zh_CN.UTF-8
RISCV=/home/huang/clonehub/RISCV/riscv
_=/usr/bin/printenv

# packages in environment at /home/huang/miniforge3/envs/chipyard:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cachecontrol              0.12.11            pyhd8ed1ab_1    conda-forge
cachecontrol-with-filecache 0.12.11            pyhd8ed1ab_1    conda-forge
cachy                     0.3.0              pyhd8ed1ab_1    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
click-default-group       1.2.2              pyhd8ed1ab_1    conda-forge
clikit                    0.6.2              pyhd8ed1ab_2    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda-lock                1.4.0              pyhd8ed1ab_2    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
crashtest                 0.4.1              pyhd8ed1ab_0    conda-forge
cryptography              39.0.1          py310h34c0648_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
distlib                   0.3.6              pyhd8ed1ab_0    conda-forge
ensureconda               1.4.3              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
filelock                  3.9.0              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.0.0              pyha770c72_0    conda-forge
importlib_metadata        6.0.0                hd8ed1ab_0    conda-forge
jaraco.classes            3.2.3              pyhd8ed1ab_0    conda-forge
jeepney                   0.8.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
keyring                   23.13.1         py310hff52083_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
markupsafe                2.1.2           py310h1fa729e_0    conda-forge
more-itertools            9.1.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.4           py310hbf28c38_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pastel                    0.2.1              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6              pyhd8ed1ab_0    conda-forge
platformdirs              3.0.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pycosat                   0.6.4           py310h5764c6d_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.5          py310h1fa729e_0    conda-forge
pylev                     1.4.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.9          he550d4f_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pyyaml                    6.0             py310h5764c6d_5    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py310h5764c6d_2    conda-forge
ruamel.yaml.clib          0.2.7           py310h1fa729e_1    conda-forge
secretstorage             3.3.3           py310hff52083_1    conda-forge
setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.6             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
virtualenv                20.19.0            pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.19.0          py310hdeb6495_1    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge

### Other Setup

Ex: Prior steps taken / Documentation Followed / etc...

### Current Behavior

I am trying to do the make in /sim/verilator, but I meet the problem that is ：
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.10:4.3.22
[error]   Not found
[error]   Not found
[error]   not found: /home/huang/.ivy2/localorg.scalameta/semanticdb-scalac_2.13.10/4.3.22/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error]   not found: https://oss.sonatype.org/service/local/repositories/releases/content/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom

I think the main problem is that the version of semanticdb is wrong， for now the available version of semanticdb is 4.7.5， I don't know the progress just set it to 4.3.22，that made the process error. So I wonder where can I change the version. Thank you in advanced!!!!

That's the whole process:
make
Running with RISCV=/home/huang/clonehub/RISCV/riscv
/home/huang/clonehub/chipyard/common.mk:128: warning: overriding recipe for target '&'
/home/huang/clonehub/chipyard/common.mk:106: warning: ignoring old recipe for target '&'
/home/huang/clonehub/chipyard/common.mk:153: warning: overriding recipe for target '&'
/home/huang/clonehub/chipyard/common.mk:128: warning: ignoring old recipe for target '&'
/home/huang/clonehub/chipyard/common.mk:157: warning: overriding recipe for target '&'
/home/huang/clonehub/chipyard/common.mk:153: warning: ignoring old recipe for target '&'
mkdir -p /home/huang/clonehub/chipyard/sims/verilator/generated-src/chipyard.TestHarness.RocketConfig
cd /home/huang/clonehub/chipyard && java -jar /home/huang/clonehub/chipyard/generators/rocket-chip/sbt-launch.jar  ";project chipyard; runMain chipyard.Generator  --target-dir /home/huang/clonehub/chipyard/sims/verilator/generated-src/chipyard.TestHarness.RocketConfig --name chipyard.TestHarness.RocketConfig --top-module chipyard.TestHarness --legacy-configs chipyard:RocketConfig "
Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Djava.io.tmpdir=/home/huang/clonehub/chipyard/.java_tmp
[info] welcome to sbt 1.5.5 (Ubuntu Java 11.0.18)
[info] loading settings for project chipyard-build from plugins.sbt ...
[info] loading project definition from /home/huang/clonehub/chipyard/project
[info] loading settings for project chipyardRoot from build.sbt ...
[info] loading settings for project hardfloat from build.sbt ...
[info] loading settings for project rocketConfig from build.sbt ...
[info] loading settings for project testchipip from build.sbt ...
[info] loading settings for project constellation from build.sbt ...
[info] loading settings for project icenet from build.sbt ...
[info] loading settings for project hwacha from build.sbt ...
[info] loading settings for project boom from build.sbt ...
[info] loading settings for project cva6 from build.sbt ...
[info] loading settings for project ibex from build.sbt ...
[info] loading settings for project sodor from build.sbt ...
[info] loading settings for project gemmini from build.sbt ...
[info] loading settings for project tapeout from build.sbt ...
[info] loading settings for project sim-build from plugins.sbt ...
[info] loading project definition from /home/huang/clonehub/chipyard/sims/firesim/sim/project
[info] loading settings for project firesim from build.sbt ...
[info] loading settings for project targetutils from build.sbt ...
[info] loading settings for project midas from build.sbt ...
[info] resolving key references (36704 settings) ...
[info] set current project to chipyardRoot (in build file:/home/huang/clonehub/chipyard/)
[info] set current project to chipyard (in build file:/home/huang/clonehub/chipyard/)
[warn] Binary version (2.12) for dependency org.scala-lang#scala-library;2.12.10
[warn] 	in edu.berkeley.cs#gemmini_2.13;3.1.0 differs from Scala binary version in project (2.13).
[warn] Binary version (2.12) for dependency org.scala-lang#scala-reflect;2.12.10
[warn] 	in edu.berkeley.cs#gemmini_2.13;3.1.0 differs from Scala binary version in project (2.13).
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.10:4.3.22
[error]   Not found
[error]   Not found
[error]   not found: /home/huang/.ivy2/localorg.scalameta/semanticdb-scalac_2.13.10/4.3.22/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error]   not found: https://oss.sonatype.org/service/local/repositories/releases/content/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error]   not found: /home/huang/.m2/repository/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (ProjectRef(uri("file:/home/huang/clonehub/chipyard/sims/firesim/sim/"), "targetutils") / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.10:4.3.22
[error]   Not found
[error]   Not found
[error]   not found: /home/huang/.ivy2/localorg.scalameta/semanticdb-scalac_2.13.10/4.3.22/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error]   not found: https://oss.sonatype.org/service/local/repositories/releases/content/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error]   not found: /home/huang/.m2/repository/org/scalameta/semanticdb-scalac_2.13.10/4.3.22/semanticdb-scalac_2.13.10-4.3.22.pom
[error] Total time: 6 s, completed Mar 6, 2023, 2:54:21 PM
make: *** [/home/huang/clonehub/chipyard/common.mk:107: /home/huang/clonehub/chipyard/sims/verilator/generated-src/chipyard.TestHarness.RocketConfig/chipyard.TestHarness.RocketConfig.fir] Error 1

### Expected Behavior

make successly

**Comment by beiming0110** [comment]
I meet the same issue, did you solve it? Here's how it was solved
