### ISSUE TITLE
setup of 1.9.1

### ISSUE THREAD

**Issue by menglinhan** [ucb-bar/chipyard#1727]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Feature Description

1.9.1 is an official release tag. I checkout this tag and run "./build-setup.sh riscv-tools". However, the setup process failed.

### Motivating Example

follow is the log of the failed processing, Is the java version not appropriate?:
sbt thinks that server is already booting because of this exception:
sbt.internal.ServerAlreadyBootingException: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: Cannot fit name [*/riscv/ocelot/chipyard_1.9.1/chipyard/.java_tmp/.sbt/sbt-socket-9111289574599218584/sbt-load.sock] in maximum unix domain socket length
	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:356)
	at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:295)
	at sbt.xMain$.getSocketOrExit(Main.scala:150)
	at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
	at sbt.xMain$.bootServerSocket$1(Main.scala:77)
	at sbt.xMain$.withStreams$1(Main.scala:85)
	at sbt.xMain$.run(Main.scala:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: Cannot fit name [*/riscv/ocelot/chipyard_1.9.1/chipyard/.java_tmp/.sbt/sbt-socket-9111289574599218584/sbt-load.sock] in maximum unix domain socket length
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.bind(UnixDomainServerSocket.java:140)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:114)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:93)
	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:350)
	... 21 more
Caused by: org.scalasbt.ipcsocket.NativeErrorException: Cannot fit name [*/riscv/ocelot/chipyard_1.9.1/chipyard/.java_tmp/.sbt/sbt-socket-9111289574599218584/sbt-load.sock] in maximum unix domain socket length
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.bind(UnixDomainSocketLibrary.java:180)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.bind(UnixDomainServerSocket.java:136)
	... 24 more
[0Jmake: *** [*/riscv/ocelot/chipyard_1.9.1/chipyard/common.mk:380: launch-sbt] Error 2

**Comment by jerryz123** [comment]
We do not guarantee maintenance or support of old releases. Try again with the latest commit on main.
