### ISSUE TITLE
Problems when running "make buildfile tutorial=sky130-openroad"

### ISSUE THREAD

**Issue by exhaust-create** [ucb-bar/chipyard#1918]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Chipyard Release: 1.11.0

### OS Setup

OS: Ubuntu 20.04 LTS

### Current Behavior

I straightly downloaded _chipyard_ according to the _chipyard_ document. When I conducted the command `./build-setup.sh esp-tools`, it stopped in the _step 3_. But I ignored this problem and directly activated the environment. But when I tried `make buildfile tutorial=sky130-openroad`, the problems were shown as below:

> [warn] Binary version (2.13) for dependency org.scala-lang#scala-library;2.13.10
> [warn]  in edu.berkeley.cs#testchipip_2.12;1.0-SNAPSHOT differs from Scala binary version in project (2.12).
> ...
> [warn]  Note: Unresolved dependencies path:
> ...
> [error] sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:rocketchip_blocks_2.12:1.6
> ...
> [error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/rocketchip_blocks_2.12/1.6/rocketchip_blocks_2.12-1.6.pom
> [error]   not found: https://oss.sonatype.org/content/repositories/snapshots/edu/berkeley/cs/rocketchip_blocks_2.12/1.6/rocketchip_blocks_2.12-1.6.pom
> [error]   not found: https://oss.sonatype.org/service/local/repositories/releases/content/edu/berkeley/cs/rocketchip_blocks_2.12/1.6/rocketchip_blocks_2.12-1.6.pom
> [error]   not found: /home/stcmj/.m2/repository/edu/berkeley/cs/rocketchip_blocks_2.12/1.6/rocketchip_blocks_2.12-1.6.po
> [error] Error downloading org.scala-graph:graph-core_2.12:1.13.5
> ...
> [error]   not found: /home/stcmj/.m2/repository/org/scala-graph/graph-core_2.12/1.13.5/graph-core_2.12-1.13.5.pom
> [error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
> [error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
> [error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
> [error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
> [error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
> [error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
> [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
> [error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
> [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
> [error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
> [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
> [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
> [error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
> [error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
> [error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
> [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
> [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
> [error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
> [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
> [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
> [error]         at sbt.Execute.work(Execute.scala:291)
> [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
> [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
> [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
> [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> [error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
> [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> [error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> [error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> [error]         at java.base/java.lang.Thread.run(Thread.java:1623)
> [error] sbt.librarymanagement.ResolveException: Error downloading org.scala-graph:graph-core_2.12:1.13.5
> ...
> [error]   not found: /home/stcmj/.m2/repository/org/scala-graph/graph-core_2.12/1.13.5/graph-core_2.12-1.13.5.pom
> [error] (ibex / update) sbt.librarymanagement.ResolveException: Error downloading org.scala-graph:graph-core_2.12:1.13.5
> ...
> /home/stcmj/chipyard/common.mk:68: /home/stcmj/chipyard/generators/ibex/ibex.mk: No such file or directory
> make: *** No rule to make target '/home/stcmj/chipyard/generators/ibex/ibex.mk'.  Stop.

How do I fix these problems?

### Expected Behavior

I want to download these files successfully.

**Comment by exhaust-create** [comment]
I found that it was the network that caused this matter.
