### ISSUE TITLE
Getting error when adding some memory-mapped registers in PWMTLModule

### ISSUE THREAD

**Issue by zxhero** [ucb-bar/chipyard#40]
Hi! 

I tried to add some memory-mapped registers in PWMTLModule:

>   regmap(
    0x00 -> Seq(
      RegField(32, zxheroperiod)),
    0x04 -> Seq(
      RegField(32, duty)),
    0x08 -> Seq(
      RegField(1, enable)),
    0x09 -> Seq(
      RegField(32, out)),
    0x0d -> Seq(
      RegField(32, addr1)
    ),
    0x11 -> Seq(
      RegField(32, waddr1)))

But I got errors when I ran `make CONFIG=PWMConfig`:

> <stdout>: Warning (simple_bus_reg): Node /soc/external-interrupts missing or empty reg/ranges property
[error] (run-main-0) java.lang.reflect.InvocationTargetException
[error] java.lang.reflect.InvocationTargetException
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at testchipip.GeneratorApp$$anonfun$circuit$1.apply(Generator.scala:22)
[error] 	at testchipip.GeneratorApp$$anonfun$circuit$1.apply(Generator.scala:19)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:49)
[error] 	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93)
[error] 	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93)
[error] 	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:297)
[error] 	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:295)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:295)
[error] 	at chisel3.Driver$.elaborate(Driver.scala:93)
[error] 	at testchipip.GeneratorApp$class.circuit(Generator.scala:19)
[error] 	at example.Generator$.circuit$lzycompute(TestHarness.scala:24)
[error] 	at example.Generator$.circuit(TestHarness.scala:24)
[error] 	at testchipip.GeneratorApp$class.generateFirrtl(Generator.scala:30)
[error] 	at example.Generator$.generateFirrtl(TestHarness.scala:24)
[error] 	at example.Generator$.delayedEndpoint$example$Generator$1(TestHarness.scala:25)
[error] 	at example.Generator$delayedInit$body.apply(TestHarness.scala:24)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at example.Generator$.main(TestHarness.scala:24)
[error] 	at example.Generator.main(TestHarness.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: Field at word 1*(8B) has bits [40, 72), which exceeds word limit.
[error] 	at scala.Predef$.require(Predef.scala:224)
[error] 	at freechips.rocketchip.regmapper.RegMapper$$anonfun$10$$anonfun$apply$8.apply(RegMapper.scala:103)
[error] 	at freechips.rocketchip.regmapper.RegMapper$$anonfun$10$$anonfun$apply$8.apply(RegMapper.scala:100)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at freechips.rocketchip.regmapper.RegMapper$$anonfun$10.apply(RegMapper.scala:100)
[error] 	at freechips.rocketchip.regmapper.RegMapper$$anonfun$10.apply(RegMapper.scala:92)
[error] 	at scala.collection.immutable.List.map(List.scala:288)
[error] 	at freechips.rocketchip.regmapper.RegMapper$.apply(RegMapper.scala:92)
[error] 	at freechips.rocketchip.tilelink.TLRegisterNode.regmap(RegisterRouter.scala:62)
[error] 	at freechips.rocketchip.tilelink.TLRegModule.regmap(RegisterRouter.scala:122)
[error] 	at example.PWMTLModule$class.$init$(PWM.scala:95)
[error] 	at example.PWMTL$$anonfun$9$$anon$2.<init>(PWM.scala:129)
[error] 	at example.PWMTL$$anonfun$9.apply(PWM.scala:129)
[error] 	at example.PWMTL$$anonfun$9.apply(PWM.scala:129)
[error] 	at freechips.rocketchip.tilelink.TLRegisterRouter.module$lzycompute(RegisterRouter.scala:142)
[error] 	at freechips.rocketchip.tilelink.TLRegisterRouter.module(RegisterRouter.scala:142)
[error] 	at freechips.rocketchip.tilelink.TLRegisterRouter.module(RegisterRouter.scala:125)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4$$anonfun$5.apply(LazyModule.scala:156)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:49)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:156)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$$anonfun$4.apply(LazyModule.scala:154)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:338)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImpLike$class.instantiate(LazyModule.scala:154)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:183)
[error] 	at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:184)
[error] 	at freechips.rocketchip.subsystem.BareSubsystemModuleImp.<init>(BaseSubsystem.scala:19)
[error] 	at freechips.rocketchip.subsystem.BaseSubsystemModuleImp.<init>(BaseSubsystem.scala:101)
[error] 	at freechips.rocketchip.subsystem.RocketSubsystemModuleImp.<init>(RocketSubsystem.scala:154)
[error] 	at example.ExampleTopModule.<init>(Top.scala:20)
[error] 	at example.ExampleTopWithPWMModule.<init>(Top.scala:35)
[error] 	at example.ExampleTopWithPWM.module$lzycompute(Top.scala:31)
[error] 	at example.ExampleTopWithPWM.module(Top.scala:31)
[error] 	at example.WithPWM$$anonfun$$lessinit$greater$3$$anonfun$apply$3$$anonfun$applyOrElse$2$$anonfun$apply$7.apply(Configs.scala:29)
[error] 	at example.WithPWM$$anonfun$$lessinit$greater$3$$anonfun$apply$3$$anonfun$applyOrElse$2$$anonfun$apply$7.apply(Configs.scala:29)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:49)
[error] 	at example.WithPWM$$anonfun$$lessinit$greater$3$$anonfun$apply$3$$anonfun$applyOrElse$2.apply(Configs.scala:29)
[error] 	at example.WithPWM$$anonfun$$lessinit$greater$3$$anonfun$apply$3$$anonfun$applyOrElse$2.apply(Configs.scala:28)
[error] 	at example.TestHarness.<init>(TestHarness.scala:15)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at testchipip.GeneratorApp$$anonfun$circuit$1.apply(Generator.scala:22)
[error] 	at testchipip.GeneratorApp$$anonfun$circuit$1.apply(Generator.scala:19)
[error] 	at chisel3.core.Module$.do_apply(Module.scala:49)
[error] 	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93)
[error] 	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93)
[error] 	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:297)
[error] 	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:295)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:295)
[error] 	at chisel3.Driver$.elaborate(Driver.scala:93)
[error] 	at testchipip.GeneratorApp$class.circuit(Generator.scala:19)
[error] 	at example.Generator$.circuit$lzycompute(TestHarness.scala:24)
[error] 	at example.Generator$.circuit(TestHarness.scala:24)
[error] 	at testchipip.GeneratorApp$class.generateFirrtl(Generator.scala:30)
[error] 	at example.Generator$.generateFirrtl(TestHarness.scala:24)
[error] 	at example.Generator$.delayedEndpoint$example$Generator$1(TestHarness.scala:25)
[error] 	at example.Generator$delayedInit$body.apply(TestHarness.scala:24)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at example.Generator$.main(TestHarness.scala:24)
[error] 	at example.Generator.main(TestHarness.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1147)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1142)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 16 s, completed Jan 23, 2019 5:47:12 PM

I am confused why I got these errors. I found code in BlockDevices.scala:

>   regmap(
    0x00 -> Seq(RegField(pAddrBits, addr)),
    0x08 -> Seq(RegField(sectorBits, offset)),
    0x0C -> Seq(RegField(sectorBits, len)),
    0x10 -> Seq(RegField(1, write)),
    0x11 -> Seq(RegField.r(tagBits, allocRead)),
    0x12 -> Seq(RegField.r(backendQueueCountBits, io.back.nallocate)),
    0x13 -> Seq(RegField.r(tagBits, io.back.complete)),
    0x14 -> Seq(RegField.r(backendQueueCountBits, io.back.ncomplete)),
    0x18 -> Seq(RegField.r(sectorBits, io.info.nsectors)),
    0x1C -> Seq(RegField.r(sectorBits, io.info.max_req_len)))

I can run `make CONFIG=SimBlockDeviceConfig` without errors. Does anyone know what's wrong with my code? 

Thanks a lot!

**Comment by alonamid** [comment]
Closing due to inactivity. Feel free to re-open if there is additional follow-up
