### ISSUE TITLE
Make WithoutTLMonitors available to Config Strings

### ISSUE THREAD

**Issue by timsnyder-siv** [ucb-bar/chipyard#583]
**Impact**: rtl

**Description**

[Originally discussed on FireSim mailing list]( https://groups.google.com/forum/#!topic/firesim/8loAr-29FbI)

When using FASED memory model in FireSim, if the Target memory interface width does not match FASED (64-bit at time of this issue) a TileLink width adapter is used to adjust the width between the Target and FASED.  This creates a small TileLink network.  If TLMonitor is attached to the network, `midas.passes.SimulationMapping` leaves the FIRRTL in an illegal state (contains `plusarg_reader` instantiations with no `extmodule` definition) and an uncaught exception is thrown in a subsequent `firrtl.passes.InferTypes` pass.

<details><summary>Observed Exception Backtrace</summary><p>

```
Form: HighForm
======== Finished Transform [Golden Gate] Simulation Mapping ========

======== Starting Transform midas.passes.xilinx.package$HostSpecialization$ ========
======== Starting Transform midas.passes.xilinx.package$DefineBUFGCE$ ========
------------------------------------------------------------------------------

... elide a number of uninteresting log lines ...

======== Finished Transform firrtl.passes.ResolveKinds$ ========

======== Starting Transform firrtl.passes.InferTypes$ =======
Exception in thread "main" firrtl.CustomTransformException: 
	at firrtl.stage.transforms.CatchCustomTransformExceptions.execute(CatchCustomTransformExceptions.scala:12)
	at firrtl.Transform.transform(Compiler.scala:222)
	at firrtl.Transform.transform$(Compiler.scala:222)
	at firrtl.stage.transforms.CatchCustomTransformExceptions.transform(CatchCustomTransformExceptions.scala:7)
	at firrtl.stage.transforms.UpdateAnnotations.$anonfun$internalTransform$2(UpdateAnnotations.scala:36)
	at firrtl.Utils$.time(Utils.scala:171)
	at firrtl.stage.transforms.UpdateAnnotations.internalTransform(UpdateAnnotations.scala:36)
	at firrtl.stage.transforms.UpdateAnnotations.internalTransform(UpdateAnnotations.scala:11)
	at firrtl.options.Translator.transform(Phase.scala:240)
	at firrtl.options.Translator.transform$(Phase.scala:240)
	at firrtl.stage.transforms.UpdateAnnotations.transform(UpdateAnnotations.scala:11)
	at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:262)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.options.DependencyManager.transform(DependencyManager.scala:255)
	at firrtl.options.DependencyManager.transform$(DependencyManager.scala:240)
	at firrtl.stage.TransformManager.transform(TransformManager.scala:14)
	at firrtl.stage.TransformManager.execute(TransformManager.scala:21)
	at midas.stage.GoldenGateCompilerPhase.transform(GoldenGateCompilerPhase.scala:36)
	at midas.stage.GoldenGateCompilerPhase.transform(GoldenGateCompilerPhase.scala:16)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:37)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
	at firrtl.options.Translator.transform(Phase.scala:240)
	at firrtl.options.Translator.transform$(Phase.scala:240)
	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
	at midas.stage.GoldenGateStage.$anonfun$run$1(GoldenGateStage.scala:29)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at midas.stage.GoldenGateStage.run(GoldenGateStage.scala:29)
	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:37)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
	at firrtl.options.Translator.transform(Phase.scala:240)
	at firrtl.options.Translator.transform$(Phase.scala:240)
	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
	at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:46)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:46)
	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:168)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at logger.Logger$.makeScope(Logger.scala:166)
	at firrtl.options.Stage.transform(Stage.scala:46)
	at firrtl.options.Stage.execute(Stage.scala:57)
	at firrtl.options.StageMain.main(Stage.scala:69)
	at midas.stage.GoldenGateMain.main(GoldenGateStage.scala)
Caused by: java.util.NoSuchElementException: key not found: plusarg_reader
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:63)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:63)
	at firrtl.passes.InferTypes$.infer_types_s$1(InferTypes.scala:53)
	at firrtl.passes.InferTypes$.$anonfun$run$14(InferTypes.scala:73)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at firrtl.ir.Block.mapStmt(IR.scala:396)
	at firrtl.Mappers$StmtMagnet$$anon$2.map(Mappers.scala:29)
	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:46)
	at firrtl.passes.InferTypes$.infer_types_s$1(InferTypes.scala:73)
	at firrtl.passes.InferTypes$.$anonfun$run$20(InferTypes.scala:84)
	at firrtl.ir.Module.mapStmt(IR.scala:869)
	at firrtl.Mappers$ModuleMagnet$$anon$13.map(Mappers.scala:106)
	at firrtl.Mappers$ModuleMap$.map$extension(Mappers.scala:119)
	at firrtl.passes.InferTypes$.infer_types$1(InferTypes.scala:84)
	at firrtl.passes.InferTypes$.$anonfun$run$22(InferTypes.scala:87)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at firrtl.passes.InferTypes$.run(InferTypes.scala:87)
	at firrtl.passes.Pass.execute(Pass.scala:12)
	at firrtl.passes.Pass.execute$(Pass.scala:12)
	at firrtl.passes.InferTypes$.execute(InferTypes.scala:11)
	at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:304)
	at firrtl.Utils$.time(Utils.scala:171)
	at firrtl.Transform.runTransform(Compiler.scala:304)
	at firrtl.Transform.runTransform$(Compiler.scala:301)
	at firrtl.passes.InferTypes$.runTransform(InferTypes.scala:11)
	at firrtl.SeqTransformBased.$anonfun$runTransforms$1(Compiler.scala:367)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.SeqTransformBased.runTransforms(Compiler.scala:367)
	at firrtl.SeqTransformBased.runTransforms$(Compiler.scala:366)
	at firrtl.SeqTransform.runTransforms(Compiler.scala:371)
	at firrtl.SeqTransform.execute(Compiler.scala:377)
	at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:304)
	at firrtl.Utils$.time(Utils.scala:171)
	at firrtl.Transform.runTransform(Compiler.scala:304)
	at firrtl.Transform.runTransform$(Compiler.scala:301)
	at firrtl.SeqTransform.runTransform(Compiler.scala:371)
	at midas.passes.MidasTransforms.$anonfun$execute$1(MidasTransforms.scala:99)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at midas.passes.MidasTransforms.execute(MidasTransforms.scala:98)
	at firrtl.Transform.transform(Compiler.scala:222)
	at firrtl.Transform.transform$(Compiler.scala:222)
	at midas.passes.MidasTransforms.transform(MidasTransforms.scala:20)
	at firrtl.stage.transforms.ExpandPrepares.execute(ExpandPrepares.scala:17)
	at firrtl.Transform.transform(Compiler.scala:222)
	at firrtl.Transform.transform$(Compiler.scala:222)
	at firrtl.stage.transforms.ExpandPrepares.transform(ExpandPrepares.scala:7)
	at firrtl.stage.transforms.CatchCustomTransformExceptions.execute(CatchCustomTransformExceptions.scala:10)
	... 49 more
```

</p></details>

As a workaround, I would like `WithoutTLMonitors` to be aliased into a package that makes it visible for use as a '_'-delimited element in the `--golden-gate-config-string` argument of `midas.stage.GoldenGateMain`

I will be submitting a PR for this shortly.

**Comment by jerryz123** [comment]
Closing, since it seems to have been resolved in FireSim.
