### ISSUE TITLE
make CONFIG=GemminiRocketConfig [error] org.eclipse.jgit.api.errors.JGitInternalException: Missing unknown 

### ISSUE THREAD

**Issue by nicolast0604** [ucb-bar/chipyard#924]
**Impact**: rtl | software | unknown | other

**Tell us about your environment:**
*Chipyard Version:* 
*OS:* 
*Other:* 

**What is the current behavior?**
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 191026ed35fd86ba471d81a130f898db2928c7f4
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:135)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:203)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:917)
	at org.eclipse.jgit.revwalk.RevWalk.parseTree(RevWalk.java:855)
	at org.eclipse.jgit.lib.IndexDiff.<init>(IndexDiff.java:290)
	at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:597)
	at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:379)
	at org.eclipse.jgit.lib.IndexDiff.diff(IndexDiff.java:354)
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:122)
	... 15 more
[error] org.eclipse.jgit.api.errors.JGitInternalException: Missing unknown 191026ed35fd86ba471d81a130f898db2928c7f4
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)

**What is the expected behavior?**

**Other information**

**Comment by alonamid** [comment]
There is not enough information in this issue description to provide assistance
