### ISSUE TITLE
SBT build errors due to .sbtopts

### ISSUE THREAD

**Issue by HaFred** [ucb-bar/chipyard#989]
**Impact**: other

**Tell us about your environment:**
*Chipyard Version:* master 
*OS:* Ubuntu 16.04.7 LTS 
*Other:* 

**What is the current behavior?**
```sbt
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Dsbt.sourcemode=true -Dsbt.workspace=$PWD/tools -Didea.managed=true -Dfile.encoding=UTF-8 -Didea.installation.dir=/snap/intellij-idea-community/323 -jar /home/zhongad/.local/share/JetBrains/IdeaIC2021.2/Scala/launcher/sbt-launch.jar
[info] welcome to sbt 1.4.9 (Private Build Java 1.8.0_292)
[info] loading global plugins from /home/zhongad/.sbt/1.0/plugins
[info] loading settings for project my_chipyard_1-5_git-build from plugins.sbt ...
[info] loading project definition from /home/zhongad/workspace/my_chipyard_1.5_git/project
[info] loading settings for project chipyardRoot from build.sbt ...
[info] loading settings for project hardfloat from build.sbt ...
[info] loading settings for project rocketConfig from build.sbt ...
[info] loading settings for project firrtl_interpreter from build.sbt ...
[info] loading settings for project treadle from build.sbt ...
[info] loading settings for project chisel_testers from build.sbt ...
[info] loading settings for project testchipip from build.sbt ...
[info] loading settings for project icenet from build.sbt ...
[info] loading settings for project hwacha from build.sbt ...
[info] loading settings for project boom from build.sbt ...
[info] loading settings for project cva6 from build.sbt ...
[info] loading settings for project sodor from build.sbt ...
[info] loading settings for project gemmini from build.sbt ...
[info] loading settings for project mdf from build.sbt ...
[info] loading settings for project barstoolsMacros from build.sbt ...
java.lang.RuntimeException: Invalid build URI (no handler available): file:/home/zhongad/workspace/my_chipyard_1.5_git/$PWD/tools/chisel3/
at scala.sys.package$.error(package.scala:30)
at sbt.internal.Load$.$anonfun$builtinLoader$1(Load.scala:483)
at sbt.internal.BuildLoader.$anonfun$apply$3(BuildLoader.scala:244)
at scala.Option.getOrElse(Option.scala:189)
at sbt.internal.BuildLoader.apply(BuildLoader.scala:244)
at sbt.internal.Load$.loadURI$1(Load.scala:548)
at sbt.internal.Load$.loadAll(Load.scala:564)
at sbt.internal.Load$.loadURI(Load.scala:494)
at sbt.internal.Load$.load(Load.scala:473)
at sbt.internal.Load$.$anonfun$apply$1(Load.scala:242)
at sbt.internal.Load$.timed(Load.scala:1382)
at sbt.internal.Load$.apply(Load.scala:242)
at sbt.internal.Load$.defaultLoad(Load.scala:55)
at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:934)
at sbt.BuiltinCommands$.doLoadProject(Main.scala:934)
at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:887)
at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
at sbt.Command$.process(Command.scala:189)
at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:243)
at scala.Option.getOrElse(Option.scala:189)
at sbt.MainLoop$.process$1(MainLoop.scala:243)
at sbt.MainLoop$.processCommand(MainLoop.scala:276)
at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
at sbt.MainLoop$.next(MainLoop.scala:163)
at sbt.MainLoop$.run(MainLoop.scala:144)
at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
at sbt.io.Using.apply(Using.scala:27)
at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
at sbt.MainLoop$.runLogged(MainLoop.scala:42)
at sbt.StandardMain$.runManaged(Main.scala:193)
at sbt.xMain$.$anonfun$run$8(Main.scala:102)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
at scala.Console$.withIn(Console.scala:230)
at sbt.internal.util.Terminal$.withIn(Terminal.scala:560)
at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
at scala.Console$.withOut(Console.scala:167)
at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:550)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
at scala.Console$.withErr(Console.scala:196)
at sbt.internal.util.Terminal$.withOut(Terminal.scala:550)
at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
at sbt.xMain$.run(Main.scala:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
at sbt.xMain.run(Main.scala:46)
at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
at xsbt.boot.Launch$.run(Launch.scala:149)
at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
at xsbt.boot.Launch$.launch(Launch.scala:159)
at xsbt.boot.Launch$.apply(Launch.scala:44)
at xsbt.boot.Launch$.apply(Launch.scala:21)
at xsbt.boot.Boot$.runImpl(Boot.scala:78)
at xsbt.boot.Boot$.run(Boot.scala:73)
at xsbt.boot.Boot$.main(Boot.scala:21)
at xsbt.boot.Boot.main(Boot.scala)
[error] Invalid build URI (no handler available): file:/home/zhongad/workspace/my_chipyard_1.5_git/$PWD/tools/chisel3/
[error] Use 'last' for the full log.
Invalid response: ';'
```

**What is the expected behavior?**
Successful build on build.sbt

**Other information**

**Comment by abejgonzalez** [comment]
As mentioned in the PR, this is addressed in PR https://github.com/ucb-bar/chipyard/pull/933 and will be updated in the next release. That changes the initial Chipyard setup to automatically add an absolute path.
